version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - -QF1001
        - -QF1003
        - -ST1005

formatters:
  enable:
    - gofmt
