# This file was generated by GoReleaser. DO NOT EDIT.
cask "mesh" do
  version "0.1.70"

  on_macos do
    on_arm do
      sha256 "c3d70fa296f6b4ebcc0d64c225a323f304311578b9856108e3e4cacb413ffae5"
      url "https://github.com/ShaulLavo/mesh/releases/download/v#{version}/mesh_darwin_arm64.tar.gz",
        verified: "github.com/ShaulLavo/mesh/"
    end
  end

  name "mesh"
  desc "Direct, resumable terminal sessions over Tailscale"
  homepage "https://github.com/ShaulLavo/mesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mesh"],
                     sudo: false
    end
  end

  # No zap stanza required
end
