# This file was generated by GoReleaser. DO NOT EDIT.
cask "mesh" do
  version "0.1.202"

  on_macos do
    on_arm do
      sha256 "7568a1c8d5333a7c8b8e9b9bdbcc020a58f923a43276acc1d99849919c0d4bce"
      url "https://github.com/ShaulLavo/mesh/releases/download/v#{version}/mesh_darwin_arm64.tar.gz",
        verified: "github.com/ShaulLavo/mesh/"
    end
  end

  name "mesh"
  desc "Direct, resumable terminal sessions over Tailscale"
  homepage "https://github.com/ShaulLavo/mesh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mesh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/mesh"],
                     sudo: false
    end
  end

  # No zap stanza required
end
