export const TOOLBAR_SNAP_MARGIN_PX = 16;
export const TOOLBAR_SNAP_ANIMATION_DURATION_MS = 250;
export const TOOLBAR_DRAG_THRESHOLD_PX = 5;
export const TOOLBAR_VELOCITY_MULTIPLIER_MS = 150;
export const TOOLBAR_COLLAPSED_SHORT_PX = 16;
export const TOOLBAR_COLLAPSED_LONG_PX = 30;
export const TOOLBAR_DEFAULT_POSITION_RATIO = 0.8;
