// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cached_services.sql

package sqlc

import (
	"context"
)

const countCachedServices = `-- name: CountCachedServices :one
SELECT count(*)
FROM cached_services
`

func (q *Queries) CountCachedServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCachedServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCachedServicesForHost = `-- name: DeleteCachedServicesForHost :exec
DELETE FROM cached_services
WHERE host_id = ?
`

func (q *Queries) DeleteCachedServicesForHost(ctx context.Context, hostID string) error {
	_, err := q.db.ExecContext(ctx, deleteCachedServicesForHost, hostID)
	return err
}

const listCachedServices = `-- name: ListCachedServices :many
SELECT host_id, private_name, name, kind, target, public_name, wake_on_request, healthy, problem, observed_at, isolate, display_name, private_host
FROM cached_services
ORDER BY host_id, name
LIMIT 8193
`

func (q *Queries) ListCachedServices(ctx context.Context) ([]CachedService, error) {
	rows, err := q.db.QueryContext(ctx, listCachedServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CachedService{}
	for rows.Next() {
		var i CachedService
		if err := rows.Scan(
			&i.HostID,
			&i.PrivateName,
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.PublicName,
			&i.WakeOnRequest,
			&i.Healthy,
			&i.Problem,
			&i.ObservedAt,
			&i.Isolate,
			&i.DisplayName,
			&i.PrivateHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCachedServicesForHost = `-- name: ListCachedServicesForHost :many
SELECT host_id, private_name, name, kind, target, public_name, wake_on_request, healthy, problem, observed_at, isolate, display_name, private_host
FROM cached_services
WHERE host_id = ?
ORDER BY name
`

func (q *Queries) ListCachedServicesForHost(ctx context.Context, hostID string) ([]CachedService, error) {
	rows, err := q.db.QueryContext(ctx, listCachedServicesForHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CachedService{}
	for rows.Next() {
		var i CachedService
		if err := rows.Scan(
			&i.HostID,
			&i.PrivateName,
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.PublicName,
			&i.WakeOnRequest,
			&i.Healthy,
			&i.Problem,
			&i.ObservedAt,
			&i.Isolate,
			&i.DisplayName,
			&i.PrivateHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCachedService = `-- name: UpsertCachedService :exec
INSERT INTO cached_services (
    host_id,
    private_name,
    name,
    kind,
    target,
    public_name,
    private_host,
    wake_on_request,
    healthy,
    problem,
    observed_at,
    isolate,
    display_name
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (host_id, name) DO UPDATE SET
	private_name = excluded.private_name,
    kind = excluded.kind,
    target = excluded.target,
    public_name = excluded.public_name,
    private_host = excluded.private_host,
    wake_on_request = excluded.wake_on_request,
    healthy = excluded.healthy,
    problem = excluded.problem,
    observed_at = excluded.observed_at,
    display_name = excluded.display_name,
    isolate = excluded.isolate
`

type UpsertCachedServiceParams struct {
	HostID        string
	PrivateName   string
	Name          string
	Kind          string
	Target        string
	PublicName    string
	PrivateHost   string
	WakeOnRequest int64
	Healthy       int64
	Problem       string
	ObservedAt    int64
	Isolate       int64
	DisplayName   string
}

func (q *Queries) UpsertCachedService(ctx context.Context, arg UpsertCachedServiceParams) error {
	_, err := q.db.ExecContext(ctx, upsertCachedService,
		arg.HostID,
		arg.PrivateName,
		arg.Name,
		arg.Kind,
		arg.Target,
		arg.PublicName,
		arg.PrivateHost,
		arg.WakeOnRequest,
		arg.Healthy,
		arg.Problem,
		arg.ObservedAt,
		arg.Isolate,
		arg.DisplayName,
	)
	return err
}
