// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edge.sql

package sqlc

import (
	"context"
)

const acknowledgeEdgeOutbox = `-- name: AcknowledgeEdgeOutbox :execrows
UPDATE edge_outbox
SET acknowledged = 1
WHERE target_id = ? AND sequence = ? AND digest = ?
`

type AcknowledgeEdgeOutboxParams struct {
	TargetID string
	Sequence int64
	Digest   string
}

func (q *Queries) AcknowledgeEdgeOutbox(ctx context.Context, arg AcknowledgeEdgeOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acknowledgeEdgeOutbox, arg.TargetID, arg.Sequence, arg.Digest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEdgeRoutesForOrigin = `-- name: DeleteEdgeRoutesForOrigin :exec
DELETE FROM edge_routes
WHERE origin_id = ?
`

func (q *Queries) DeleteEdgeRoutesForOrigin(ctx context.Context, originID string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgeRoutesForOrigin, originID)
	return err
}

const deleteEdgeSnapshot = `-- name: DeleteEdgeSnapshot :exec
DELETE FROM edge_snapshots
WHERE origin_id = ?
`

func (q *Queries) DeleteEdgeSnapshot(ctx context.Context, originID string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgeSnapshot, originID)
	return err
}

const getEdgeOutbox = `-- name: GetEdgeOutbox :one
SELECT target_id, sequence, digest, snapshot_json, acknowledged
FROM edge_outbox
WHERE target_id = ?
`

func (q *Queries) GetEdgeOutbox(ctx context.Context, targetID string) (EdgeOutbox, error) {
	row := q.db.QueryRowContext(ctx, getEdgeOutbox, targetID)
	var i EdgeOutbox
	err := row.Scan(
		&i.TargetID,
		&i.Sequence,
		&i.Digest,
		&i.SnapshotJson,
		&i.Acknowledged,
	)
	return i, err
}

const getEdgeOutboxSize = `-- name: GetEdgeOutboxSize :one
SELECT length(snapshot_json)
FROM edge_outbox
WHERE target_id = ?
`

func (q *Queries) GetEdgeOutboxSize(ctx context.Context, targetID string) (*int64, error) {
	row := q.db.QueryRowContext(ctx, getEdgeOutboxSize, targetID)
	var length *int64
	err := row.Scan(&length)
	return length, err
}

const getEdgeRoute = `-- name: GetEdgeRoute :one
SELECT origin_id, public_name, service_name, wake_on_request
FROM edge_routes
WHERE public_name = ? AND service_name = ?
`

type GetEdgeRouteParams struct {
	PublicName  string
	ServiceName string
}

func (q *Queries) GetEdgeRoute(ctx context.Context, arg GetEdgeRouteParams) (EdgeRoute, error) {
	row := q.db.QueryRowContext(ctx, getEdgeRoute, arg.PublicName, arg.ServiceName)
	var i EdgeRoute
	err := row.Scan(
		&i.OriginID,
		&i.PublicName,
		&i.ServiceName,
		&i.WakeOnRequest,
	)
	return i, err
}

const getEdgeSnapshot = `-- name: GetEdgeSnapshot :one
SELECT origin_id, target_id, sequence, digest, issued_at, expires_at, last_seen_at, signature
FROM edge_snapshots
WHERE origin_id = ?
`

func (q *Queries) GetEdgeSnapshot(ctx context.Context, originID string) (EdgeSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getEdgeSnapshot, originID)
	var i EdgeSnapshot
	err := row.Scan(
		&i.OriginID,
		&i.TargetID,
		&i.Sequence,
		&i.Digest,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Signature,
	)
	return i, err
}

const insertEdgeRoute = `-- name: InsertEdgeRoute :exec
INSERT INTO edge_routes (origin_id, public_name, service_name, wake_on_request)
VALUES (?, ?, ?, ?)
`

type InsertEdgeRouteParams struct {
	OriginID      string
	PublicName    string
	ServiceName   string
	WakeOnRequest int64
}

func (q *Queries) InsertEdgeRoute(ctx context.Context, arg InsertEdgeRouteParams) error {
	_, err := q.db.ExecContext(ctx, insertEdgeRoute,
		arg.OriginID,
		arg.PublicName,
		arg.ServiceName,
		arg.WakeOnRequest,
	)
	return err
}

const listEdgeRoutes = `-- name: ListEdgeRoutes :many
SELECT origin_id, public_name, service_name, wake_on_request
FROM edge_routes
ORDER BY public_name, service_name
`

func (q *Queries) ListEdgeRoutes(ctx context.Context) ([]EdgeRoute, error) {
	rows, err := q.db.QueryContext(ctx, listEdgeRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdgeRoute{}
	for rows.Next() {
		var i EdgeRoute
		if err := rows.Scan(
			&i.OriginID,
			&i.PublicName,
			&i.ServiceName,
			&i.WakeOnRequest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgeRoutesForOrigin = `-- name: ListEdgeRoutesForOrigin :many
SELECT origin_id, public_name, service_name, wake_on_request
FROM edge_routes
WHERE origin_id = ?
ORDER BY public_name, service_name
`

func (q *Queries) ListEdgeRoutesForOrigin(ctx context.Context, originID string) ([]EdgeRoute, error) {
	rows, err := q.db.QueryContext(ctx, listEdgeRoutesForOrigin, originID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdgeRoute{}
	for rows.Next() {
		var i EdgeRoute
		if err := rows.Scan(
			&i.OriginID,
			&i.PublicName,
			&i.ServiceName,
			&i.WakeOnRequest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgeSnapshots = `-- name: ListEdgeSnapshots :many
SELECT origin_id, target_id, sequence, digest, issued_at, expires_at, last_seen_at, signature
FROM edge_snapshots
ORDER BY origin_id
`

func (q *Queries) ListEdgeSnapshots(ctx context.Context) ([]EdgeSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listEdgeSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdgeSnapshot{}
	for rows.Next() {
		var i EdgeSnapshot
		if err := rows.Scan(
			&i.OriginID,
			&i.TargetID,
			&i.Sequence,
			&i.Digest,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.Signature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEdgeOutbox = `-- name: UpsertEdgeOutbox :execrows
INSERT INTO edge_outbox (target_id, sequence, digest, snapshot_json, acknowledged)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (target_id) DO UPDATE SET
    sequence = excluded.sequence,
    digest = excluded.digest,
    snapshot_json = excluded.snapshot_json,
    acknowledged = excluded.acknowledged
WHERE excluded.sequence > edge_outbox.sequence
`

type UpsertEdgeOutboxParams struct {
	TargetID     string
	Sequence     int64
	Digest       string
	SnapshotJson []byte
	Acknowledged int64
}

func (q *Queries) UpsertEdgeOutbox(ctx context.Context, arg UpsertEdgeOutboxParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertEdgeOutbox,
		arg.TargetID,
		arg.Sequence,
		arg.Digest,
		arg.SnapshotJson,
		arg.Acknowledged,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertEdgeSnapshot = `-- name: UpsertEdgeSnapshot :exec
INSERT INTO edge_snapshots (
    origin_id, target_id, sequence, digest, issued_at, expires_at, last_seen_at, signature
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (origin_id) DO UPDATE SET
    target_id = excluded.target_id,
    sequence = excluded.sequence,
    digest = excluded.digest,
    issued_at = excluded.issued_at,
    expires_at = excluded.expires_at,
    last_seen_at = excluded.last_seen_at,
    signature = excluded.signature
`

type UpsertEdgeSnapshotParams struct {
	OriginID   string
	TargetID   string
	Sequence   int64
	Digest     string
	IssuedAt   int64
	ExpiresAt  int64
	LastSeenAt int64
	Signature  []byte
}

func (q *Queries) UpsertEdgeSnapshot(ctx context.Context, arg UpsertEdgeSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertEdgeSnapshot,
		arg.OriginID,
		arg.TargetID,
		arg.Sequence,
		arg.Digest,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.Signature,
	)
	return err
}
