// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hosts.sql

package sqlc

import (
	"context"
)

const getHost = `-- name: GetHost :one
SELECT id, alias, mesh_identity, tailscale_name, last_seen_at
FROM hosts
WHERE id = ?
`

func (q *Queries) GetHost(ctx context.Context, id string) (Host, error) {
	row := q.db.QueryRowContext(ctx, getHost, id)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.MeshIdentity,
		&i.TailscaleName,
		&i.LastSeenAt,
	)
	return i, err
}

const listHosts = `-- name: ListHosts :many
SELECT id, alias, mesh_identity, tailscale_name, last_seen_at
FROM hosts
ORDER BY last_seen_at DESC, id
`

func (q *Queries) ListHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Host{}
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.MeshIdentity,
			&i.TailscaleName,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHost = `-- name: UpsertHost :one
INSERT INTO hosts (
    id,
    alias,
    mesh_identity,
    tailscale_name,
    last_seen_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    alias = excluded.alias,
    mesh_identity = excluded.mesh_identity,
    tailscale_name = excluded.tailscale_name,
    last_seen_at = excluded.last_seen_at
RETURNING id, alias, mesh_identity, tailscale_name, last_seen_at
`

type UpsertHostParams struct {
	ID            string
	Alias         *string
	MeshIdentity  string
	TailscaleName *string
	LastSeenAt    int64
}

func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) (Host, error) {
	row := q.db.QueryRowContext(ctx, upsertHost,
		arg.ID,
		arg.Alias,
		arg.MeshIdentity,
		arg.TailscaleName,
		arg.LastSeenAt,
	)
	var i Host
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.MeshIdentity,
		&i.TailscaleName,
		&i.LastSeenAt,
	)
	return i, err
}
