// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type AppName struct {
	Hostname string
	OwnerID  string
	Active   int64
}

type CachedService struct {
	HostID      string
	PrivateName string
	Name        string
	Kind        string
	Target      string
	Healthy     int64
	Problem     string
	ObservedAt  int64
	Isolate     int64
	DisplayName string
	PrivateHost string
}

type Host struct {
	ID            string
	MeshIdentity  string
	TailscaleName *string
	LastSeenAt    int64
}

type PrivateAppState struct {
	Key  string
	Data []byte
}

type Service struct {
	Name        string
	Kind        string
	Target      string
	Isolate     int64
	Listens     string
	Demand      string
	LocalOnly   int64
	DisplayName string
	PrivateHost string
}

type Session struct {
	ID                 string
	HostID             string
	Command            string
	Cwd                string
	State              string
	CreatedAt          int64
	LastAttachedAt     *int64
	ExitCode           *int64
	LastOutputSequence int64
}
