// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Host struct {
	ID            string
	Alias         *string
	MeshIdentity  string
	TailscaleName *string
	LastSeenAt    int64
}

type Service struct {
	Name          string
	Kind          string
	Target        string
	PublicName    string
	WakeOnRequest int64
}

type Session struct {
	ID                 string
	HostID             string
	Command            string
	Cwd                string
	State              string
	CreatedAt          int64
	LastAttachedAt     *int64
	ExitCode           *int64
	LastOutputSequence int64
}
