// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type CachedService struct {
	HostID        string
	PrivateName   string
	Name          string
	Kind          string
	Target        string
	PublicName    string
	WakeOnRequest int64
	Healthy       int64
	Problem       string
	ObservedAt    int64
}

type EdgeOutbox struct {
	TargetID     string
	Sequence     int64
	Digest       string
	SnapshotJson []byte
	Acknowledged int64
}

type EdgeRoute struct {
	OriginID      string
	PublicName    string
	ServiceName   string
	WakeOnRequest int64
}

type EdgeSnapshot struct {
	OriginID   string
	TargetID   string
	Sequence   int64
	Digest     string
	IssuedAt   int64
	ExpiresAt  int64
	LastSeenAt int64
	Signature  []byte
}

type Host struct {
	ID            string
	Alias         *string
	MeshIdentity  string
	TailscaleName *string
	LastSeenAt    int64
}

type Service struct {
	Name          string
	Kind          string
	Target        string
	PublicName    string
	WakeOnRequest int64
}

type Session struct {
	ID                 string
	HostID             string
	Command            string
	Cwd                string
	State              string
	CreatedAt          int64
	LastAttachedAt     *int64
	ExitCode           *int64
	LastOutputSequence int64
}
