// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"
)

const deleteService = `-- name: DeleteService :execrows
DELETE FROM services
WHERE name = ?
`

func (q *Queries) DeleteService(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteService, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getService = `-- name: GetService :one
SELECT name, kind, target, public_name, wake_on_request, isolate
FROM services
WHERE name = ?
`

func (q *Queries) GetService(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, name)
	var i Service
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.PublicName,
		&i.WakeOnRequest,
		&i.Isolate,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT name, kind, target, public_name, wake_on_request, isolate
FROM services
ORDER BY name
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.PublicName,
			&i.WakeOnRequest,
			&i.Isolate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertService = `-- name: UpsertService :one
INSERT INTO services (
    name,
    kind,
    target,
    public_name,
    wake_on_request,
    isolate
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    kind = excluded.kind,
    target = excluded.target,
    public_name = excluded.public_name,
    wake_on_request = excluded.wake_on_request,
    isolate = excluded.isolate
RETURNING name, kind, target, public_name, wake_on_request, isolate
`

type UpsertServiceParams struct {
	Name          string
	Kind          string
	Target        string
	PublicName    string
	WakeOnRequest int64
	Isolate       int64
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, upsertService,
		arg.Name,
		arg.Kind,
		arg.Target,
		arg.PublicName,
		arg.WakeOnRequest,
		arg.Isolate,
	)
	var i Service
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.PublicName,
		&i.WakeOnRequest,
		&i.Isolate,
	)
	return i, err
}
