// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"
)

const deleteService = `-- name: DeleteService :execrows
DELETE FROM services
WHERE name = ?
`

func (q *Queries) DeleteService(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteService, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getService = `-- name: GetService :one
SELECT name, kind, target, isolate, listens, demand, local_only, display_name, private_host
FROM services
WHERE name = ?
`

func (q *Queries) GetService(ctx context.Context, name string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, name)
	var i Service
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.Isolate,
		&i.Listens,
		&i.Demand,
		&i.LocalOnly,
		&i.DisplayName,
		&i.PrivateHost,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT name, kind, target, isolate, listens, demand, local_only, display_name, private_host
FROM services
ORDER BY name
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.Name,
			&i.Kind,
			&i.Target,
			&i.Isolate,
			&i.Listens,
			&i.Demand,
			&i.LocalOnly,
			&i.DisplayName,
			&i.PrivateHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertService = `-- name: UpsertService :one
INSERT INTO services (
    name,
    kind,
    target,
    private_host,
    isolate,
    listens,
    demand,
    local_only,
    display_name
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    kind = excluded.kind,
    target = excluded.target,
    private_host = excluded.private_host,
    isolate = excluded.isolate,
    listens = excluded.listens,
    demand = excluded.demand,
    display_name = excluded.display_name,
    local_only = excluded.local_only
RETURNING name, kind, target, isolate, listens, demand, local_only, display_name, private_host
`

type UpsertServiceParams struct {
	Name        string
	Kind        string
	Target      string
	PrivateHost string
	Isolate     int64
	Listens     string
	Demand      string
	LocalOnly   int64
	DisplayName string
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, upsertService,
		arg.Name,
		arg.Kind,
		arg.Target,
		arg.PrivateHost,
		arg.Isolate,
		arg.Listens,
		arg.Demand,
		arg.LocalOnly,
		arg.DisplayName,
	)
	var i Service
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Target,
		&i.Isolate,
		&i.Listens,
		&i.Demand,
		&i.LocalOnly,
		&i.DisplayName,
		&i.PrivateHost,
	)
	return i, err
}
