// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
)

const getSession = `-- name: GetSession :one
SELECT id, host_id, command, cwd, state, created_at, last_attached_at, exit_code, last_output_sequence
FROM sessions
WHERE host_id = ? AND id = ?
`

type GetSessionParams struct {
	HostID string
	ID     string
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.HostID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Command,
		&i.Cwd,
		&i.State,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.ExitCode,
		&i.LastOutputSequence,
	)
	return i, err
}

const interruptActiveSessionsForHost = `-- name: InterruptActiveSessionsForHost :exec
UPDATE sessions
SET state = 'interrupted', exit_code = NULL
WHERE host_id = ? AND state IN ('running', 'detached')
`

func (q *Queries) InterruptActiveSessionsForHost(ctx context.Context, hostID string) error {
	_, err := q.db.ExecContext(ctx, interruptActiveSessionsForHost, hostID)
	return err
}

const listHostSessions = `-- name: ListHostSessions :many
SELECT id, host_id, command, cwd, state, created_at, last_attached_at, exit_code, last_output_sequence
FROM sessions
WHERE host_id = ?
ORDER BY created_at DESC, id
`

func (q *Queries) ListHostSessions(ctx context.Context, hostID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listHostSessions, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Command,
			&i.Cwd,
			&i.State,
			&i.CreatedAt,
			&i.LastAttachedAt,
			&i.ExitCode,
			&i.LastOutputSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByState = `-- name: ListSessionsByState :many
SELECT id, host_id, command, cwd, state, created_at, last_attached_at, exit_code, last_output_sequence
FROM sessions
WHERE state = ?
ORDER BY created_at DESC, host_id, id
`

func (q *Queries) ListSessionsByState(ctx context.Context, state string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.Command,
			&i.Cwd,
			&i.State,
			&i.CreatedAt,
			&i.LastAttachedAt,
			&i.ExitCode,
			&i.LastOutputSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionState = `-- name: SetSessionState :one
UPDATE sessions
SET state = ?, exit_code = ?
WHERE host_id = ? AND id = ?
RETURNING id, host_id, command, cwd, state, created_at, last_attached_at, exit_code, last_output_sequence
`

type SetSessionStateParams struct {
	State    string
	ExitCode *int64
	HostID   string
	ID       string
}

func (q *Queries) SetSessionState(ctx context.Context, arg SetSessionStateParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, setSessionState,
		arg.State,
		arg.ExitCode,
		arg.HostID,
		arg.ID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Command,
		&i.Cwd,
		&i.State,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.ExitCode,
		&i.LastOutputSequence,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (
    id,
    host_id,
    command,
    cwd,
    state,
    created_at,
    last_attached_at,
    exit_code,
    last_output_sequence
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (host_id, id) DO UPDATE SET
    command = excluded.command,
    cwd = excluded.cwd,
    state = excluded.state,
    created_at = excluded.created_at,
    last_attached_at = CASE
        WHEN excluded.last_attached_at IS NULL THEN sessions.last_attached_at
        WHEN sessions.last_attached_at IS NULL THEN excluded.last_attached_at
        ELSE MAX(sessions.last_attached_at, excluded.last_attached_at)
    END,
    exit_code = excluded.exit_code,
    last_output_sequence = MAX(sessions.last_output_sequence, excluded.last_output_sequence)
RETURNING id, host_id, command, cwd, state, created_at, last_attached_at, exit_code, last_output_sequence
`

type UpsertSessionParams struct {
	ID                 string
	HostID             string
	Command            string
	Cwd                string
	State              string
	CreatedAt          int64
	LastAttachedAt     *int64
	ExitCode           *int64
	LastOutputSequence int64
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, upsertSession,
		arg.ID,
		arg.HostID,
		arg.Command,
		arg.Cwd,
		arg.State,
		arg.CreatedAt,
		arg.LastAttachedAt,
		arg.ExitCode,
		arg.LastOutputSequence,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.Command,
		&i.Cwd,
		&i.State,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.ExitCode,
		&i.LastOutputSequence,
	)
	return i, err
}
